version: '3.1'

services:
  tba:
    depends_on:
      - tb-db
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_USERNAME=${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD=${BOT_DB_PASSWORD}
    restart: always
  tb-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'prod_tb_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
