version: '3.1'

services:
  tb-db:
    image: mysql:8.0
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev_tb_db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'dev_tb_db'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'